tasks:
  - before: |
      echo "Starting Before"
  - init: |
      echo "Starting Init"
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - command: |
      echo "Starting Command"
image: public.ecr.aws/vlaaaaaaad/gitpod-terraform:latest